### PR TITLE
Major fixes

### PR DESCRIPTION
**Pull request by danielepantaleone**
This PR fixes some major bugs I have experienced:

FIXES:
- Plugin configuration file was missing `[settings]` section
- Plugin was loading the group level as `string` and thus all checks of the form `if client.maxLevel > self._maxLevel:` were failing
- Methods `getBanIps` and `getTempBanIps` were returning `None` instead of the list of banned ips

IMPROVEMENTS:
- Optimized SQL queries to return just the data we need
- Updated plugin module structure to use a 'module directory' for easier install
- Fixed usage of deprecated method `startup()`
- Added automated tests

### CODE REVIEW

**Comment by thomasleveil** [comment]
what about adding a .travis.yml file also?

**Comment by danielepantaleone** [comment]
Done :smiley:

**Comment by markweirath** [comment]
wow... you saved my life! ;)
Thanks buddy! :+1:

**Comment by danielepantaleone** [comment]
You're welcome :smiley:

**Pull request merged**
